# Generated by Django 4.0 on 2022-01-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financebackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.TextField()),
                ('age_estimation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='isDeactivated',
            new_name='is_deactivated',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='isExceeded',
            new_name='is_exceeded',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='isExpense',
            new_name='is_expense',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='categoryID',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('monthly_target_saving', models.FloatField()),
                ('bank_balance', models.FloatField()),
                ('pin_code', models.IntegerField()),
                ('is_deactivated', models.BooleanField()),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financebackend.avatar')),
                ('theme_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financebackend.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('amount', models.FloatField()),
                ('is_expense', models.BooleanField()),
                ('date_time', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financebackend.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financebackend.user')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('impact', models.FloatField()),
                ('is_deactivated', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financebackend.category')),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.FloatField()),
                ('remark', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financebackend.user')),
            ],
        ),
        migrations.AddField(
            model_name='avatar',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financebackend.gender'),
        ),
    ]
