# Generated by Django 4.0 on 2022-01-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financebackend', '0002_avatar_gender_theme_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='age_estimation',
        ),
        migrations.AddField(
            model_name='avatar',
            name='max_age_estimation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avatar',
            name='min_age_estimation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
