# Generated by Django 4.0 on 2022-01-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financebackend', '0003_remove_avatar_age_estimation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
    ]
