# Generated by Django 3.2.9 on 2022-01-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financebackend', '0005_category_date_time_relatedword_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financebackend.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatedword',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financebackend.user'),
            preserve_default=False,
        ),
    ]
