# Generated by Django 3.2.9 on 2022-01-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financebackend', '0006_auto_20220110_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dateTime',
            new_name='date_time',
        ),
    ]
