# Generated by Django 4.0 on 2022-01-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financebackend', '0007_rename_datetime_user_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_expense',
        ),
    ]
