# Generated by Django 4.0 on 2022-01-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financebackend', '0009_alter_category_is_exceeded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedword',
            name='user',
        ),
    ]
